# Use the official Apache HTTP Server image from Docker Hub
FROM httpd:2.4

# Copy the HTML file into the document root of Apache
COPY index.html /usr/local/apache2/htdocs/

# Expose port 80 to allow communication to/from the server
EXPOSE 80
